# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{proj4rb}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Guilhem Vellut"]
  s.date = %q{2010-10-20}
  s.description = %q{Proj4rb is a ruby binding for the Proj.4 Carthographic Projection library, that supports conversions between a very large number of geographic coordinate systems and datums.}
  s.email = %q{guilhem.vellut@gmail.com}
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "Changelog",
     "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    "Changelog",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "data/GL27",
     "data/MD",
     "data/TN",
     "data/WI",
     "data/WO",
     "data/conus",
     "data/epsg",
     "data/epsg-deprecated",
     "data/esri",
     "data/esri.extra",
     "data/hawaii",
     "data/nad.lst",
     "data/nad27",
     "data/nad83",
     "data/ntv1_can.dat",
     "data/null",
     "data/other.extra",
     "data/proj_def.dat",
     "data/prvi",
     "data/stgeorge",
     "data/stlrnc",
     "data/stpaul",
     "data/world",
     "example/basic.rb",
     "example/list-datums.rb",
     "example/list-ellipsoids.rb",
     "example/list-errors.rb",
     "example/list-prime-meridians.rb",
     "example/list-projection-types.rb",
     "example/list-units.rb",
     "example/version.rb",
     "ext/extconf.rb",
     "ext/mingw/proj4_ruby.so",
     "ext/mingw/rakefile.rb",
     "ext/projrb.c",
     "ext/vc/proj4_ruby.sln",
     "ext/vc/proj4_ruby.vcproj",
     "lib/proj4rb.rb",
     "test/helper.rb",
     "test/test_constants.rb",
     "test/test_create_projection.rb",
     "test/test_datums.rb",
     "test/test_ellipsoids.rb",
     "test/test_errors.rb",
     "test/test_init_projection.rb",
     "test/test_prime_meridians.rb",
     "test/test_projection_type.rb",
     "test/test_simple_projection.rb",
     "test/test_transform.rb",
     "test/test_units.rb"
  ]
  s.homepage = %q{http://github.com/Caged/proj4rb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9")
  s.requirements = ["Proj.4 C library"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby bindings for the Proj.4 Carthographic Projection library}
  s.test_files = [
    "test/helper.rb",
     "test/test_constants.rb",
     "test/test_create_projection.rb",
     "test/test_datums.rb",
     "test/test_ellipsoids.rb",
     "test/test_errors.rb",
     "test/test_init_projection.rb",
     "test/test_prime_meridians.rb",
     "test/test_projection_type.rb",
     "test/test_simple_projection.rb",
     "test/test_transform.rb",
     "test/test_units.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

